### ISSUE TITLE
geohash does not work with JOSM 14253+

### ISSUE THREAD

**Issue by don-vip** [Telenav/geohash-plugin#1]
`Main` was deprecated. It's gone in [JOSM 14253](https://josm.openstreetmap.de/changeset/14253/josm/).

`Main.pref` must be almost always replaced by `Config.getPref()` (introduced in [JOSM 12847](https://josm.openstreetmap.de/changeset/12847/josm)).
Few advanced methods can only be called from `Preferences.main()` (introduced in [JOSM 14149](https://josm.openstreetmap.de/changeset/14149/josm)).

Plugin must be [updated](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/jdk=JDK8/2081/warnings3Result/type.-79151137/) and a new version released.

**Comment by don-vip** [comment]
Did you fix the issue? The plugin is no longer flagged as incompatible.

**Comment by beataj-telenav** [comment]
Thanks for reporting the issue, yesterday we have managed to fix it
