### ISSUE TITLE
Please provide install instructions and/or prebuilt binaries

### ISSUE THREAD

**Issue by ItalyPaleAle** [Telenav/geohash-plugin#2]
While I admit that I'm a total novice with JOSM, the 3-point setup instructions below did not work for me, and "ant" gave me error for missing symbols.

Can you please provide complete installation instructions, or maybe prebuilt binaries?

**Comment by laurad-telenav** [comment]
I'm glad it did. This information is already documented here:
https://wiki.openstreetmap.org/wiki/JOSM/Plugins#Installation
The plugin installation process is common for all JOSM plugins.
